#!/usr/bin/bash
#多源复制MMSS 之S
############################安装mysql######################################
cat >>/etc/yum.repos.d/mysql.repo <<-EOF
[mysql]
name=mysql
baseurl=ftp://10.18.42.185/mysql
gpgcheck=0
EOF
yum repolist
yum -y install mysql-community-server-5.7.19-1.el7.x86_64
##############################配置环境######################################
ip123=`ip a|grep 'inet 192'|awk '{print $2}' |awk -F"/" '{print $1}'`
hou=${ip123:12:3}
passwd=centos
systemctl start mysqld
chown -R mysql.mysql /var/lib/mysql
aaa=`grep 'temporary password' /var/log/mysqld.log |awk '{print $NF}'`
mysqladmin -uroot -p"$aaa" password '(TianYunYang123)'
cat >> /etc/my.cnf <<-EOF
log-bin
slow_query_log=1
slow_query_log_file=/var/log/mysql-slow/slow.log
long_query_time=3
master-info-repository=TABLE
relay-log-info-repository=TABLE
server-id=$hou
EOF
systemctl restart mysqld
############################### 数据导入 ####################################
mysql -p'(TianYunYang123)' < master1
log1=`grep 'master1' ./master1 |awk -F"'" '{print $2}'`
pos1=`grep 'master1' ./master1 |awk -F"," '{print $2}'|awk -F";" '{print $1}'|awk -F"=" '{print $2}'`

log2=`grep 'master2-bin.000' ./master2 |awk -F"'" '{print $2}'`
pos2=`grep 'master2-bin.000' ./master2 |awk -F"," '{print $2}'|awk -F";" '{print $1}'|awk -F"=" '{print $2}'`

mysql -p'(TianYunYang123)' -e"change master to master_host='master1', master_user='rep',master_password='(TianYunYang123)',master_log_file='$log1',master_log_pos=$pos1 for channel 'master1-channel';"
mysql -p'(TianYunYang123)' -e"change master to master_host='master2', master_user='rep',master_password='(TianYunYang123)',master_log_file='$log2',master_log_pos=$pos2 for channel 'master2-channel';"
mysql -p'(TianYunYang123)'<<-EOF
start slave;
show slave status\G;
\q
EOF
